In [1]:
!pip install datasets evaluate transformers[sentencepiece]
!apt install git-lfs

/bin/bash: /home/rkannan/miniconda3/envs/richard_tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)
Collecting datasets
  Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 149.6 kB/s eta 0:00:00[36m0:00:01m eta 0:00:01
Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 298.8 kB/s eta 0:00:001m327.6 kB/s eta 0:00:01
Requirement already satisfied: transformers[sentencepiece] in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (4.31.0)
Requirement already satisfied: numpy>=1.17 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from datasets) (1.23.5)
Requirement already satisfied: aiohttp in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from datasets) (3.8.5)
Requirement already satisfied: pandas in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from datasets) (1.5.3)
Requirement already satisfied: fsspec[http]<=2024.9.0,>=2023.1.0 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from datasets) (2023.6.0)
Requirement already satisfied: filelock in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from datasets) (3.12.0)
Collecting requests>=2.32.2
  Downloading requests-2.32.3-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 324.7 kB/s eta 0:00:001m345.8 kB/s eta 0:00:01
Requirement already satisfied: multiprocess<0.70.17 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from datasets) (0.70.15)
Requirement already satisfied: pyyaml>=5.1 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from datasets) (6.0)
Collecting huggingface-hub>=0.23.0
  Downloading huggingface_hub-0.27.0-py3-none-any.whl (450 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 450.5/450.5 kB 323.5 kB/s eta 0:00:00[36m0:00:01[36m0:00:01:01
Collecting tqdm>=4.66.3
  Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 527.4 kB/s eta 0:00:001m523.9 kB/s eta 0:00:01
Requirement already satisfied: packaging in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from datasets) (22.0)
Collecting pyarrow>=15.0.0
  Downloading pyarrow-18.1.0-cp39-cp39-manylinux_2_28_x86_64.whl (40.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 MB 237.0 kB/s eta 0:00:00m eta 0:00:01[36m0:00:05
Collecting xxhash
  Downloading xxhash-3.5.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (193 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.9/193.9 kB 334.8 kB/s eta 0:00:00 kB/s eta 0:00:01
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from datasets) (0.3.7)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from transformers[sentencepiece]) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from transformers[sentencepiece]) (0.3.1)
Requirement already satisfied: regex!=2019.12.17 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from transformers[sentencepiece]) (2023.6.3)
Requirement already satisfied: protobuf in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from transformers[sentencepiece]) (3.19.6)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from transformers[sentencepiece]) (0.1.99)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from aiohttp->datasets) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from aiohttp->datasets) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from aiohttp->datasets) (6.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from aiohttp->datasets) (3.1.0)
Requirement already satisfied: attrs>=17.3.0 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from huggingface-hub>=0.23.0->datasets) (4.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from requests>=2.32.2->datasets) (2022.12.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from requests>=2.32.2->datasets) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from requests>=2.32.2->datasets) (3.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from pandas->datasets) (2022.7.1)
Requirement already satisfied: six>=1.5 in /home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)
Installing collected packages: xxhash, tqdm, requests, pyarrow, huggingface-hub, datasets, evaluate
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.65.0
    Uninstalling tqdm-4.65.0:
      Successfully uninstalled tqdm-4.65.0
  Attempting uninstall: requests
    Found existing installation: requests 2.28.2
    Uninstalling requests-2.28.2:
      Successfully uninstalled requests-2.28.2
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.16.4
    Uninstalling huggingface-hub-0.16.4:
      Successfully uninstalled huggingface-hub-0.16.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-datasets 4.9.2 requires protobuf>=3.20, but you have protobuf 3.19.6 which is incompatible.
Successfully installed datasets-3.2.0 evaluate-0.4.3 huggingface-hub-0.27.0 pyarrow-18.1.0 requests-2.32.3 tqdm-4.67.1 xxhash-3.5.0
/bin/bash: /home/rkannan/miniconda3/envs/richard_tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

### You will need to setup git, adapt your email and name in the following cell.

In [53]:
!git config --global user.email "richannan24@gmail.com"
!git config --global user.name "Astonish24"

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/bin/bash: /home/rkannan/miniconda3/envs/richard_tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/bin/bash: /home/rkannan/miniconda3/envs/richard_tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)

### You will also need to be logged in to the Hugging Face Hub. Execute the following and enter your credentials.

In [55]:
from huggingface_hub import notebook_login

notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

### Dataset

In [56]:
import numpy as np
import pandas as pd

In [217]:
import pandas as pd

# Read the CSV file
data = pd.read_csv('sample _questions_for_pilot_test.csv')

# Display the first few rows
data_df = pd.DataFrame(data)
raw_datasets = data_df
raw_datasets.dropna(inplace=True)
raw_datasets.head()

,question,answers,context
0,What is the primary focus of the integrative p...,The primary focus is to integrate sustainable ...,This integrative process seeks to incorporate ...
1,Why is human health prioritized in the integra...,Human health is prioritized to ensure that bui...,This integrative process seeks to incorporate ...
2,At what stage should the cross-discipline appr...,The cross-discipline approach should begin dur...,This integrative process seeks to incorporate ...
3,What document is prepared to establish the fou...,The Owner’s Project Requirements (OPR) document.,This integrative process seeks to incorporate ...
4,What is the purpose of the preliminary LEED me...,What is the purpose of the preliminary LEED mT...,This integrative process seeks to incorporate ...

In [218]:
from difflib import SequenceMatcher

def find_answer_start_position(answer, context):
    """
    Finds the start position of the answer in the context and returns it in a specific format.
    
    Parameters:
    answer (str): The answer string to search for.
    context (str): The context string to search in.
    
    Returns:
    dict: A dictionary in the format {'text': [answer], 'answer_start': [start_index]}.
    """
    match = SequenceMatcher(None, context, answer).find_longest_match(0, len(context), 0, len(answer))
    if match.size > 0:
        start_index = match.a  # Start index in the context
        return {'text': [answer], 'answer_start': [start_index]}
    return {'text': [answer], 'answer_start': [-1]}  # -1 indicates the answer was not found

# # Example usage
# answer = "The primary focus is to integrate sustainable and cost-effective green design and construction strategies with a core emphasis on human health"
# context = """This integrative process seeks to incorporate sustainable and cost-effective green design and construction strategies with a core focus on human health. By embedding health as a primary evaluative criterion in building design, construction, and operational strategies, this approach promotes innovative practices that foster high-performance healing environments for patients, caregivers, and staff."""

# result = find_answer_start_position(answer, context)
# print(result)

In [220]:
answer_index = []
for i in range(0, raw_datasets.shape[0]):
    answer_index.append(find_answer_start_position(raw_datasets.iloc[i]['answers'],raw_datasets.iloc[i]['question']))
raw_datasets['answer_idx'] = answer_index
# Assuming df is your DataFrame
unique_numbers = [f"unique-{i}" for i in range(raw_datasets.shape[0])]
raw_datasets['id'] = unique_numbers
raw_datasets.to_json()

'{"question":{"0":"What is the primary focus of the integrative process in healthcare projects?","1":"Why is human health prioritized in the integrative process?","2":"At what stage should the cross-discipline approach begin in healthcare projects?","3":"What document is prepared to establish the foundation for a health-focused environment in healthcare projects?","4":"What is the purpose of the preliminary LEED meeting in healthcare projects?","5":"When is it ideal to conduct the preliminary LEED meeting?","6":"How many professionals should the integrated project team include at minimum?","7":"Who might be part of the integrated project team in a healthcare project?","8":"What is the purpose of having a comprehensive project team in healthcare projects?","9":"What collaborative session must be held to enhance planning, and who should attend?","10":"How long should the design charrette session last?","11":"At what project phase is the design charrette ideally conducted?","12":"What is the ultimate goal of the integrative process for healthcare projects?","13":"How does the integrative process support LEED certification goals?","14":"What is the main purpose of the Integrative Process credit in BD&C projects?","15":"Why is it important for the Integrative Process to begin during the pre-design phase?","16":"What specific analysis is required for energy-related systems in the Integrative Process?","17":"How does assessing \\u201cmassing and orientation\\u201d impact the energy efficiency of a building in the Integrative Process?","18":"What role does the water budget analysis play in the Integrative Process?","19":"Why should nonpotable water sources, such as rainwater, be included in the water budget analysis?","20":"What might happen if a BD&C project does not incorporate the Integrative Process starting at pre-design?","21":"How does the Integrative Process affect decisions about HVAC and lighting systems in BD&C projects?","22":"In what ways might multifunctional spaces contribute to the Integrative Process?","23":"Does the Integrative Process require both energy and water analyses for LEED certification in BD&C?","24":"What is the primary goal of the Location and Transportation (LT) credits in the LEED framework?","25":"How many points can projects earn for the LEED for Neighborhood Development Location credit?","26":"Why are projects that pursue the LEED for Neighborhood Development Location credit ineligible for other Location and Transportation credits?","27":"What are some project types that are eligible for the LEED for Neighborhood Development Location credit?","28":"How does the Sensitive Land Protection credit help reduce ecological impact?","29":"What are two options a project has to qualify for the Sensitive Land Protection credit?","30":"Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit?","31":"What minor improvements are allowed within the buffer zones of sensitive lands, and why?","32":"How does the Sensitive Land Protection credit support the broader mission of LEED?","33":"What additional steps are allowed for managing hazardous or dying trees within sensitive land areas?","34":"What does the term \\"abut\\" mean in property law?\\n\\n","35":"What are access trails, and what features might they include?","36":"What is an accessory building, and how does it differ from an accessory dwelling unit (ADU)?","37":"How is an accessory dwelling unit (ADU) different from the main residence on a property?","38":"What is the primary function of an accessory structure in relation to the principal structure on a property?","39":"How does the North Carolina Sedimentation Pollution Control Act relate to land development regulations?","40":"What does the term \\"addition\\" specifically refer to in the context of flood damage prevention regulations?","41":"What types of facilities are not considered part of \\"airport facilities\\" under the city\'s regulations?","42":"What is the purpose of an alley in relation to property access?","43":"How does the Certified Arborist designation contribute to tree care practices?","44":"What defines an Area of Special Flood Hazard and how is it determined?","45":"How does articulation enhance the visual appeal of a building?","46":"What is considered a \\"banner\\" according to the City of Greensboro\'s Land Development Ordinance?","47":"What is the \\"base flood\\" and how is its elevation determined?","48":"What qualifies a room as a \\"bedroom\\"?","49":"What does \\"being conducted\\" mean in relation to land-disturbing activities?","50":"What is the purpose of a Best Management Practice (BMP)?","51":"What is a \\"block face\\" in relation to building setbacks?","52":"What is a \\"brewpub\\"?","53":"What is the function of a \\"buffer zone\\" in land development?","54":"What is the definition of a \\"building\\" in the Greensboro Land Development Ordinance?","55":"What is the \\"building height\\"?","56":"What is considered a \\"building marker\\"?","57":"What does \\"built-upon area\\" (BUA) refer to in a development project?","58":"What is the purpose of a \\"business incubator\\"?","59":"How does a business incubator help a neighborhood\'s image?","60":"What does \\"caliper size\\" measure in relation to trees?","61":"What is the difference between a \\"canopy tree\\" and other tree species?","62":"What is the key difference between back-lit and reverse channel letters?","63":"What is the purpose of front-lit channel letters?","64":"What services does a chartered home provide?","65":"What defines a chemical storage facility under flood damage prevention regulations?","66":"Who can access a club or lodge facility?","67":"What is a commercial message?","68":"What activities can take place in a community garden?","69":"What defines the ownership in a condominium?","70":"What is the purpose of a connection in stormwater management?","71":"What items are typically sold at convenience stores with fuel pumps?","72":"What distinguishes a Critical Root Zone from a \\"dripline\\"?","73":"What is a craft distillery","74":"What is the purpose of Current Conditions Hydrology in flood studies?","75":"Based on the information provided what places in the Greensboro area can be considered Dance Clubs.","76":"What materials are typically used to construct an uncovered deck?","77":"What does density credit allow in terms of development?","78":"How is a detached building or structure defined?","79":"What type of permit is required for development activities in a floodplain?"},"answers":{"0":"The primary focus is to integrate sustainable and cost-effective green design and construction strategies with a core emphasis on human health ","1":"Human health is prioritized to ensure that building design, construction, and operational strategies foster high-performance healing environments for patients, caregivers, and staff.","2":"The cross-discipline approach should begin during the programming and pre-design phases.","3":"The Owner\\u2019s Project Requirements (OPR) document.","4":"What is the purpose of the preliminary LEED mThe preliminary LEED meeting is held to develop a LEED action plan, determining the certification level, selecting LEED credits, and assigning responsibility for meeting requirements.eeting in healthcare projects?","5":"Ideally, the meeting should be conducted before the schematic design phase.","6":"The integrated project team should include a minimum of four professionals in addition to the owner or the owner\\u2019s representative.","7":"The team might include professionals like the capital budget manager, civil engineer, landscape architect, building designer, mechanical engineer, and other relevant experts.","8":"The comprehensive project team ensures an interdisciplinary approach to design and decision-making, integrating diverse expertise to achieve sustainable, health-centered outcomes.","9":"A design charrette must be held, involving all team members for optimal integration of green strategies.","10":"The design charrette should last a minimum of four hours.","11":" Ideally, the design charrette is conducted before the schematic design phase.","12":"The ultimate goal is to create a healthier built environment for users and support broader health and environmental objectives.","13":"By following the integrative steps, healthcare projects ensure compliance with sustainable, health-centered solutions aligned with LEED certification standards.","14":"The primary purpose of the Integrative Process credit is to enhance high-performance and cost-effective project outcomes by analyzing and leveraging the interrelationships among various building systems early in the design process.","15":"Starting in the pre-design phase allows the project team to maximize synergy across disciplines and systems, integrating insights into the Owner\\u2019s Project Requirements (OPR) and Basis of Design (BOD) for more efficient and sustainable outcomes.","16":"A preliminary energy modeling analysis, often called a \\u201csimple box\\u201d model, is required to explore strategies for reducing energy loads by assessing factors such as site conditions, massing, orientation, and envelope attributes before the schematic design phase.","17":"Assessing massing and orientation influences HVAC sizing, lighting requirements, energy consumption, and the potential for renewable energy integration, helping improve overall energy efficiency.","18":"The water budget analysis is crucial for identifying methods to reduce potable water use and exploring nonpotable sources, optimizing systems like plumbing, rainwater management, and landscaping for greater water efficiency.","19":"Including nonpotable sources like rainwater helps reduce dependency on municipal water supplies, potentially lowering operational costs and enhancing sustainability by addressing multiple water demands, such as for irrigation and indoor fixtures.","20":"If the Integrative Process is not started early, the project may miss opportunities to optimize system interactions, leading to higher costs, less efficient design, and potentially reduced LEED certification outcomes.","21":"The Integrative Process encourages analyzing energy efficiency factors like site orientation, massing, and interior lighting needs, which often leads to downsizing or simplifying HVAC and lighting systems for better efficiency and sustainability.","22":"By incorporating multifunctional spaces, projects can reduce the overall building area and optimize space usage, thereby lowering energy and water demands and creating a more efficient, adaptable design.","23":"Yes, the Integrative Process credit requires comprehensive energy and water analyses, documenting how these studies inform design decisions across systems to support sustainable outcomes essential for LEED certification.","24":"The primary goal is to encourage project development on sites that enhance environmental sustainability, reduce urban sprawl, and promote healthier lifestyles.","25":"Projects can earn between 3 to 16 points, depending on project type and certification level.","26":"Because this credit provides a comprehensive approach to sustainable neighborhood integration, making additional LT credits unnecessary.","27":"Eligible project types include New Construction, Core & Shell, Schools, and Healthcare.","28":"By awarding points to projects that avoid environmentally sensitive lands, the credit minimizes the ecological impact of development.","29":"Projects can either locate on previously developed land or choose land that does not meet criteria for sensitivity, such as prime farmland or floodplains.","30":"Avoiding such land ensures the protection of resources essential for food production, ecological health, and water management.","31":"Minor improvements such as narrow bicycle paths, native plant restoration, and small clearings are allowed to support sustainable access and appreciation of these natural areas.","32":"By guiding projects toward site selection that protects and enhances local ecosystems and reduces environmental degradation, it supports LEED\'s mission to promote sustainable development practices.","33":"Hazardous or dying trees can be removed based on an assessment by an arborist, supporting safe and sustainable site access.","34":"\\"Abut\\" refers to properties or land features that are directly connected along a common border. This term is commonly used in zoning and property law to describe adjacent properties or structures.","35":"Access trails are pedestrian pathways designed to provide access to surface water or natural areas. They can be made from pervious or impervious surfaces and may include features like boardwalks, steps, handrails, and signage for safety and navigation.","36":"An accessory building is a detached structure on the same property as the primary building, typically used for purposes like storage, workshops, or garages. Unlike an accessory dwelling unit (ADU), which is a secondary living space, an accessory building is not intended for residential use.","37":"An accessory dwelling unit (ADU) is a smaller living space that is either part of the primary home or located in a separate structure on the same property. While the main residence is typically the primary family living space, the ADU is secondary and often used for guests, renters, or family members.","38":"An accessory structure is a detached building that serves a function incidental to the principal structure. It is located on the same zoning lot and typically supports or complements the use of the main building, such as a garage, shed, or similar secondary structure.","39":"The North Carolina Sedimentation Pollution Control Act of 1973 establishes rules and regulations aimed at controlling sedimentation and preventing pollution. It is part of the framework that governs land development, especially in activities that may result in sediment runoff or environmental degradation.","40":"In the context of flood damage prevention regulations, an \\"addition\\" refers to any extension or increase in the floor area or height of an existing building or structure. This definition specifically applies to flood damage regulations, which may require additional considerations for structures in flood-prone areas.","41":"Facilities that are not considered part of \\"airport facilities\\" include satellite parking lots, retail and commercial developments outside of the terminal area (such as rental car facilities), and other secondary buildings like hotels or freestanding offices. These are excluded unless they are directly related to airport operations or managed by a governmental entity, such as an airport authority.","42":"An alley provides secondary access to properties, often located at the rear of a parcel, and is typically used for services, deliveries, or additional vehicle access.","43":"A Certified Arborist is recognized for their expertise in tree care, having passed an ISA-administered exam that covers all aspects of tree health, maintenance, and proper care techniques.","44":"An Area of Special Flood Hazard is land within the floodplain with at least a 1% chance of flooding annually, determined by hydrological data and flood risk assessments.","45":"Articulation adds variety and visual interest to building exteriors by emphasizing architectural elements like doorways, windows, massing, and decorative details.","46":"A banner is a lightweight fabric or similar material mounted to a pole or building, not including national, state, municipal, or official institutional flags","47":"The base flood has a 1% chance of occurring each year, and its elevation (BFE) is determined through hydrological studies and engineering methodologies.","48":"A bedroom is a room furnished with a bed, primarily used for sleeping, and includes an exterior exit for emergency escape.","49":"\\"Being conducted\\" means that a land-disturbing activity has begun, but permanent stabilization of the site has not yet been completed.","50":"BMPs are used to reduce non-point source pollution and help achieve water quality protection goals, either individually or in combination.","51":"A block face refers to the specific side of a block used to reference setbacks or the bulk of buildings along that side.","52":"A brewpub is an eating and drinking establishment that produces fewer than 15,000 barrels of malt beverages annually.","53":"A buffer zone is a strip of land next to a lake or natural watercourse, typically designed to protect the waterbody from development or pollution.","54":"A building is any structure with a roof supported by walls or columns, used for residential, business, industrial, or other purposes.","55":"Building height is measured vertically from the average elevation of the finished grade to the topmost section of the roof.","56":"A building marker is a sign indicating the name, date, or other details about a building, typically made of permanent materials like bronze or cut into masonry.","57":"Built-upon area refers to portions of a development covered by impervious or partially impervious surfaces, such as buildings, roads, and parking lots.","58":"A business incubator provides affordable space, equipment, and services to support small, start-up firms in their early stages, encouraging business growth, job creation, and economic diversification.","59":"It enhances the neighborhood\\u00eds image by positioning it as a center for innovation and entrepreneurship through job creation and business development.","60":"Caliper size measures the trunk diameter of a tree at planting, taken 6 inches above the ground for smaller trees (4 inches or less in trunk diameter) and 12 inches for larger trees.","61":"A canopy tree grows to a height of 40 feet or more, with a minimum crown width of 30 feet, making it significantly larger than other tree species.","62":"Back-lit channel letters create a \\"halo\\" effect by shining light behind them, while reverse channel letters have opaque faces and sides, focusing on design rather than illumination.","63":"Front-lit channel letters allow illumination to shine through their translucent faces for visibility.","64":"Chartered homes provide room, board, personal care, and habilitation services in a family-like setting.","65":"It is a location, inside or adjacent to a building, designated for storing chemicals or reactive products to comply with flood damage prevention rules.","66":"Only annual dues-paying members, their occasional guests, and other parties on a non-regular rental basis can access it.\\n","67":"It is a sign or representation that advertises or promotes a business, product, or service.","68":"Growing food and ornamental crops for personal or group use, consumption, or donation.","69":"Private ownership of designated portions and collective ownership of common elements by unit owners.\\n","70":"To divert or transmit stormwater drainage, impacting the city\'s storm sewer system.","71":"Fuel, automotive products","72":"The Critical Root Zone is a radius around a tree based on its trunk diameter at ground level.","73":"A facility that contains a tasting room and produces less than 15,000 gallons of craft spirits per year.","74":"It identifies flood discharges based on land-use conditions existing at the time of the study, aiding in flood damage prevention.","75":"Ghost Bar,XO social lounge etc","76":"Uncovered decks are commonly made of lumber or similar materials.","77":"Density credit allows the transfer of development potential to other parts of the same parcel or contiguous land in a common development plan.","78":"It is a building or structure that is not structurally attached to or integrated with another.","79":"A floodplain development permit is required for any development activities, including structural and non-structural changes, under Flood Damage Prevention reg

In [221]:
from datasets import Dataset, DatasetDict
import pandas as pd

# Assume raw_datasets is your pandas DataFrame
# Split the dataset into train and validation sets (adjust proportions as needed)
train_df = raw_datasets.sample(frac=0.8, random_state=42)  # 80% for training
validation_df = raw_datasets.drop(train_df.index)  # Remaining 20% for validation

# Convert pandas DataFrames to Hugging Face Datasets
train_dataset = Dataset.from_pandas(train_df)
validation_dataset = Dataset.from_pandas(validation_df)

# Create the DatasetDict
dataset_dict = DatasetDict({
    "train": train_dataset,
    "validation": validation_dataset
})


# Display dataset summary
print(dataset_dict)
raw_datasets = dataset_dict

DatasetDict({
    train: Dataset({
        features: ['question', 'answers', 'context', 'answer_idx', 'id', '__index_level_0__'],
        num_rows: 64
    })
    validation: Dataset({
        features: ['question', 'answers', 'context', 'answer_idx', 'id', '__index_level_0__'],
        num_rows: 16
    })
})

In [222]:
print(raw_datasets['train'][0:1]['answer_idx'])

[{'answer_start': [128], 'text': ['Avoiding such land ensures the protection of resources essential for food production, ecological health, and water management.']}]

In [223]:
# from sklearn.model_selection import train_test_split

# # Split the data into training and validation sets
# raw_datasets, raw_datasets_val = train_test_split(
#     raw_datasets,  # The DataFrame containing the processed data
#     test_size=0.2,  # Percentage of the data to be used for validation (e.g., 20%)
#     random_state=42,  # For reproducibility
#     shuffle=True  # Shuffle the data before splitting
# )

# # Split the validation set into validation and test sets
# raw_datasets_val, raw_datasets_test = train_test_split(
#     raw_datasets_val,  # The previously created validation DataFrame
#     test_size=0.1,  # Split 50% of the validation set into test data
#     random_state=42,  # For reproducibility
#     shuffle=True  # Shuffle the data before splitting
# )

# # Display the sizes of the splits
# print(f"Training set size: {len(raw_datasets)}")
# print(f"Validation set size: {len(raw_datasets_val)}")
# print(f"Test set size: {len(raw_datasets_test)}")

In [224]:
print("Context: ", raw_datasets["train"][0]["context"])
print("Question: ", raw_datasets["train"][0]["question"])
print("Answer: ", raw_datasets["train"][0]["answer_idx"])

Context:  The Sensitive Land Protection credit is another important component of the LT credits, awarding 1 to 2 points to projects that avoid environmentally sensitive lands, thus minimizing the ecological impact of development. The credit offers two options: locating on previously developed land or choosing land that does not meet criteria for sensitivity, such as prime farmland, floodplains, or habitats for endangered species. This protection extends to water bodies and wetlands, requiring a minimum buffer of 100 feet for water bodies and 50 feet for wetlands. Projects aiming for this credit must be careful to avoid land identified as critical for agriculture, ecosystems, or water retention. Sensitive habitats are defined by regulations like the U.S. Endangered Species Act, NatureServe classifications, or equivalent local standards, ensuring protection for vulnerable ecosystems and species. For projects on previously developed land or those that meet sensitive land standards, minor improvements may be allowed within the specified buffer zones. These improvements are restricted to environmentally considerate features, such as narrow bicycle paths, native plant restoration, and small clearings for public enjoyment. Additional allowances are made for removing hazardous or dying trees based on arborist assessment and brownfield remediation efforts, with the goal of restoring natural areas while supporting sustainable access for building users. By meeting the Sensitive Land Protection criteria, projects contribute to LEED’s overarching mission to develop sustainable sites that protect and enhance local ecosystems, responsibly manage natural resources, and reduce environmental degradation through thoughtful site selection and preservation strategies.)
Question:  Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit?
Answer:  {'answer_start': [128], 'text': ['Avoiding such land ensures the protection of resources essential for food production, ecological health, and water management.']}

In [225]:
raw_datasets["train"].filter(lambda x: len(x["answer_idx"]["text"]) != 1)

Filter:   0%|          | 0/64 [00:00<?, ? examples/s]

Dataset({
    features: ['question', 'answers', 'context', 'answer_idx', 'id', '__index_level_0__'],
    num_rows: 0
})

In [226]:
print(raw_datasets["validation"][0]["answer_idx"])
print(raw_datasets["validation"][2]["answer_idx"])

{'answer_start': [19], 'text': ['Human health is prioritized to ensure that building design, construction, and operational strategies foster high-performance healing environments for patients, caregivers, and staff.']}
{'answer_start': [16], 'text': ['The primary purpose of the Integrative Process credit is to enhance high-performance and cost-effective project outcomes by analyzing and leveraging the interrelationships among various building systems early in the design process.']}

In [227]:
print(raw_datasets["validation"][2]["context"])
print(raw_datasets["validation"][2]["question"])

The Integrative Process credit for BD&C projects aims to enhance high-performance, cost-effective outcomes by analyzing and leveraging the interrelationships among different building systems. This credit applies across various project types, including new construction, core and shell, schools, retail, data centers, warehouses, distribution centers, hospitality, and healthcare facilities. The process begins during the pre-design phase and continues through the design stages to maximize synergy across disciplines and building systems. By incorporating these interdisciplinary insights into essential project documents, such as the Owner’s Project Requirements (OPR) and Basis of Design (BOD), teams can ensure the resulting design aligns with both operational efficiency and sustainability goals.
What is the main purpose of the Integrative Process credit in BD&C projects?

In [228]:
from transformers import AutoTokenizer

model_checkpoint = "bert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

/home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [229]:
tokenizer.is_fast

True

In [230]:
context = raw_datasets["train"][0]["context"]
question = raw_datasets["train"][0]["question"]

inputs = tokenizer(question, context)
tokenizer.decode(inputs["input_ids"])

'[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] The Sensitive Land Protection credit is another important component of the LT credits, awarding 1 to 2 points to projects that avoid environmentally sensitive lands, thus minimizing the ecological impact of development. The credit offers two options : locating on previously developed land or choosing land that does not meet criteria for sensitivity, such as prime farmland, floodplains, or habitats for endangered species. This protection extends to water bodies and wetlands, requiring a minimum buffer of 100 feet for water bodies and 50 feet for wetlands. Projects aiming for this credit must be careful to avoid land identified as critical for agriculture, ecosystems, or water retention. Sensitive habitats are defined by regulations like the U. S. Endangered Species Act, NatureServe classifications, or equivalent local standards, ensuring protection for vulnerable ecosystems and species. For projects on previously developed land or those that meet sensitive land standards, minor improvements may be allowed within the specified buffer zones. These improvements are restricted to environmentally considerate features, such as narrow bicycle paths, native plant restoration, and small clearings for public enjoyment. Additional allowances are made for removing hazardous or dying trees based on arborist assessment and brownfield remediation efforts, with the goal of restoring natural areas while supporting sustainable access for building users. By meeting the Sensitive Land Protection criteria, projects contribute to LEED ’ s overarching mission to develop sustainable sites that protect and enhance local ecosystems, responsibly manage natural resources, and reduce environmental degradation through thoughtful site selection and preservation strategies. ) [SEP]'

In [231]:
inputs = tokenizer(
    question,
    context,
    max_length=100,
    truncation="only_second",
    stride=50,
    return_overflowing_tokens=True,
)

for ids in inputs["input_ids"]:
    print(tokenizer.decode(ids))

[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] The Sensitive Land Protection credit is another important component of the LT credits, awarding 1 to 2 points to projects that avoid environmentally sensitive lands, thus minimizing the ecological impact of development. The credit offers two options : locating on previously developed land or choosing land that does not meet criteria for sensitivity, such as prime farmland, floodplains, [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] to projects that avoid environmentally sensitive lands, thus minimizing the ecological impact of development. The credit offers two options : locating on previously developed land or choosing land that does not meet criteria for sensitivity, such as prime farmland, floodplains, or habitats for endangered species. This protection extends to water bodies and wetlands, requiring a minimum buffer of 100 [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] two options : locating on previously developed land or choosing land that does not meet criteria for sensitivity, such as prime farmland, floodplains, or habitats for endangered species. This protection extends to water bodies and wetlands, requiring a minimum buffer of 100 feet for water bodies and 50 feet for wetlands. Projects aiming for this credit must be careful to avoid land [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] as prime farmland, floodplains, or habitats for endangered species. This protection extends to water bodies and wetlands, requiring a minimum buffer of 100 feet for water bodies and 50 feet for wetlands. Projects aiming for this credit must be careful to avoid land identified as critical for agriculture, ecosystems, or water retention. Sensitive habitats are defined by regulations like the [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] wetlands, requiring a minimum buffer of 100 feet for water bodies and 50 feet for wetlands. Projects aiming for this credit must be careful to avoid land identified as critical for agriculture, ecosystems, or water retention. Sensitive habitats are defined by regulations like the U. S. Endangered Species Act, NatureServe classifications, or equivalent local standards, [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] this credit must be careful to avoid land identified as critical for agriculture, ecosystems, or water retention. Sensitive habitats are defined by regulations like the U. S. Endangered Species Act, NatureServe classifications, or equivalent local standards, ensuring protection for vulnerable ecosystems and species. For projects on previously developed land or those that meet sensitive land standards [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP]sitive habitats are defined by regulations like the U. S. Endangered Species Act, NatureServe classifications, or equivalent local standards, ensuring protection for vulnerable ecosystems and species. For projects on previously developed land or those that meet sensitive land standards, minor improvements may be allowed within the specified buffer zones. These improvements are restricted to environmentally considerate [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] classifications, or equivalent local standards, ensuring protection for vulnerable ecosystems and species. For projects on previously developed land or those that meet sensitive land standards, minor improvements may be allowed within the specified buffer zones. These improvements are restricted to environmentally considerate features, such as narrow bicycle paths, native plant restoration, and small clearings for public enjoyment. Additional [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] land or those that meet sensitive land standards, minor improvements may be allowed within the specified buffer zones. These improvements are restricted to environmentally considerate features, such as narrow bicycle paths, native plant restoration, and small clearings for public enjoyment. Additional allowances are made for removing hazardous or dying trees based on arborist assessment and brownfield re [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] improvements are restricted to environmentally considerate features, such as narrow bicycle paths, native plant restoration, and small clearings for public enjoyment. Additional allowances are made for removing hazardous or dying trees based on arborist assessment and brownfield remediation efforts, with the goal of restoring natural areas while supporting sustainable access for building users. By meeting [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] small clearings for public enjoyment. Additional allowances are made for removing hazardous or dying trees based on arborist assessment and brownfield remediation efforts, with the goal of restoring natural areas while supporting sustainable access for building users. By meeting the Sensitive Land Protection criteria, projects contribute to LEED ’ s overarching mission to develop [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP]rborist assessment and brownfield remediation efforts, with the goal of restoring natural areas while supporting sustainable access for building users. By meeting the Sensitive Land Protection criteria, projects contribute to LEED ’ s overarching mission to develop sustainable sites that protect and enhance local ecosystems, responsibly manage natural resources, and reduce environmental degradation [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] sustainable access for building users. By meeting the Sensitive Land Protection criteria, projects contribute to LEED ’ s overarching mission to develop sustainable sites that protect and enhance local ecosystems, responsibly manage natural resources, and reduce environmental degradation through thoughtful site selection and preservation strategies. ) [SEP]

In [232]:
inputs = tokenizer(
    question,
    context,
    max_length=100,
    truncation="only_second",
    stride=50,
    return_overflowing_tokens=True,
)

for ids in inputs["input_ids"]:
    print(tokenizer.decode(ids))

[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] The Sensitive Land Protection credit is another important component of the LT credits, awarding 1 to 2 points to projects that avoid environmentally sensitive lands, thus minimizing the ecological impact of development. The credit offers two options : locating on previously developed land or choosing land that does not meet criteria for sensitivity, such as prime farmland, floodplains, [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] to projects that avoid environmentally sensitive lands, thus minimizing the ecological impact of development. The credit offers two options : locating on previously developed land or choosing land that does not meet criteria for sensitivity, such as prime farmland, floodplains, or habitats for endangered species. This protection extends to water bodies and wetlands, requiring a minimum buffer of 100 [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] two options : locating on previously developed land or choosing land that does not meet criteria for sensitivity, such as prime farmland, floodplains, or habitats for endangered species. This protection extends to water bodies and wetlands, requiring a minimum buffer of 100 feet for water bodies and 50 feet for wetlands. Projects aiming for this credit must be careful to avoid land [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] as prime farmland, floodplains, or habitats for endangered species. This protection extends to water bodies and wetlands, requiring a minimum buffer of 100 feet for water bodies and 50 feet for wetlands. Projects aiming for this credit must be careful to avoid land identified as critical for agriculture, ecosystems, or water retention. Sensitive habitats are defined by regulations like the [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] wetlands, requiring a minimum buffer of 100 feet for water bodies and 50 feet for wetlands. Projects aiming for this credit must be careful to avoid land identified as critical for agriculture, ecosystems, or water retention. Sensitive habitats are defined by regulations like the U. S. Endangered Species Act, NatureServe classifications, or equivalent local standards, [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] this credit must be careful to avoid land identified as critical for agriculture, ecosystems, or water retention. Sensitive habitats are defined by regulations like the U. S. Endangered Species Act, NatureServe classifications, or equivalent local standards, ensuring protection for vulnerable ecosystems and species. For projects on previously developed land or those that meet sensitive land standards [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP]sitive habitats are defined by regulations like the U. S. Endangered Species Act, NatureServe classifications, or equivalent local standards, ensuring protection for vulnerable ecosystems and species. For projects on previously developed land or those that meet sensitive land standards, minor improvements may be allowed within the specified buffer zones. These improvements are restricted to environmentally considerate [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] classifications, or equivalent local standards, ensuring protection for vulnerable ecosystems and species. For projects on previously developed land or those that meet sensitive land standards, minor improvements may be allowed within the specified buffer zones. These improvements are restricted to environmentally considerate features, such as narrow bicycle paths, native plant restoration, and small clearings for public enjoyment. Additional [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] land or those that meet sensitive land standards, minor improvements may be allowed within the specified buffer zones. These improvements are restricted to environmentally considerate features, such as narrow bicycle paths, native plant restoration, and small clearings for public enjoyment. Additional allowances are made for removing hazardous or dying trees based on arborist assessment and brownfield re [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] improvements are restricted to environmentally considerate features, such as narrow bicycle paths, native plant restoration, and small clearings for public enjoyment. Additional allowances are made for removing hazardous or dying trees based on arborist assessment and brownfield remediation efforts, with the goal of restoring natural areas while supporting sustainable access for building users. By meeting [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] small clearings for public enjoyment. Additional allowances are made for removing hazardous or dying trees based on arborist assessment and brownfield remediation efforts, with the goal of restoring natural areas while supporting sustainable access for building users. By meeting the Sensitive Land Protection criteria, projects contribute to LEED ’ s overarching mission to develop [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP]rborist assessment and brownfield remediation efforts, with the goal of restoring natural areas while supporting sustainable access for building users. By meeting the Sensitive Land Protection criteria, projects contribute to LEED ’ s overarching mission to develop sustainable sites that protect and enhance local ecosystems, responsibly manage natural resources, and reduce environmental degradation [SEP]
[CLS] Why is it important to avoid land identified as critical for agriculture, ecosystems, or water retention in the Sensitive Land Protection credit? [SEP] sustainable access for building users. By meeting the Sensitive Land Protection criteria, projects contribute to LEED ’ s overarching mission to develop sustainable sites that protect and enhance local ecosystems, responsibly manage natural resources, and reduce environmental degradation through thoughtful site selection and preservation strategies. ) [SEP]

In [233]:
inputs = tokenizer(
    question,
    context,
    max_length=100,
    truncation="only_second",
    stride=50,
    return_overflowing_tokens=True,
    return_offsets_mapping=True,
)
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'offset_mapping', 'overflow_to_sample_mapping'])

In [234]:
inputs["overflow_to_sample_mapping"]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [235]:
inputs = tokenizer(
    raw_datasets["train"][2:6]["question"],
    raw_datasets["train"][2:6]["context"],
    max_length=100,
    truncation="only_second",
    stride=50,
    return_overflowing_tokens=True,
    return_offsets_mapping=True,
)

print(f"The 4 examples gave {len(inputs['input_ids'])} features.")
print(f"Here is where each comes from: {inputs['overflow_to_sample_mapping']}.")

The 4 examples gave 17 features.
Here is where each comes from: [0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3].

In [236]:
answers = raw_datasets["train"][2:6]["answer_idx"]
print(answers)

[{'answer_start': [3], 'text': ['By incorporating multifunctional spaces, projects can reduce the overall building area and optimize space usage, thereby lowering energy and water demands and creating a more efficient, adaptable design.']}, {'answer_start': [6], 'text': ['Minor improvements such as narrow bicycle paths, native plant restoration, and small clearings are allowed to support sustainable access and appreciation of these natural areas.']}, {'answer_start': [1], 'text': ['The water budget analysis is crucial for identifying methods to reduce potable water use and exploring nonpotable sources, optimizing systems like plumbing, rainwater management, and landscaping for greater water efficiency.']}, {'answer_start': [56], 'text': ['By awarding points to projects that avoid environmentally sensitive lands, the credit minimizes the ecological impact of development.']}]

In [237]:
answers = raw_datasets["train"][2:6]["answer_idx"]
start_positions = []
end_positions = []

for i, offset in enumerate(inputs["offset_mapping"]):
    sample_idx = inputs["overflow_to_sample_mapping"][i]
    answer = answers[sample_idx]
    start_char = answer["answer_start"][0]
    end_char = answer["answer_start"][0] + len(answer["text"][0])
    sequence_ids = inputs.sequence_ids(i)

    # Find the start and end of the context
    idx = 0
    while sequence_ids[idx] != 1:
        idx += 1
    context_start = idx
    while sequence_ids[idx] == 1:
        idx += 1
    context_end = idx - 1

    # If the answer is not fully inside the context, label is (0, 0)
    if offset[context_start][0] > start_char or offset[context_end][1] < end_char:
        start_positions.append(0)
        end_positions.append(0)
    else:
        # Otherwise it's the start and end token positions
        idx = context_start
        while idx <= context_end and offset[idx][0] <= start_char:
            idx += 1
        start_positions.append(idx - 1)

        idx = context_end
        while idx >= context_start and offset[idx][1] >= end_char:
            idx -= 1
        end_positions.append(idx + 1)

start_positions, end_positions

([19, 0, 0, 0, 0, 19, 0, 0, 0, 18, 0, 0, 0, 23, 0, 0, 0],
 [60, 0, 0, 0, 0, 46, 0, 0, 0, 59, 0, 0, 0, 49, 0, 0, 0])

In [238]:
idx = 0
sample_idx = inputs["overflow_to_sample_mapping"][idx]
answer = answers[sample_idx]["text"][0]

start = start_positions[idx]
end = end_positions[idx]
labeled_answer = tokenizer.decode(inputs["input_ids"][idx][start : end + 1])

print(f"Theoretical answer: {answer}, labels give: {labeled_answer}")

Theoretical answer: By incorporating multifunctional spaces, projects can reduce the overall building area and optimize space usage, thereby lowering energy and water demands and creating a more efficient, adaptable design., labels give: Energy - related systems are a core focus within the Integrative Process, requiring a preliminary energy modeling analysis, often called a “ simple box ” model, completed before the schematic design phase. This

In [239]:
idx = 4
sample_idx = inputs["overflow_to_sample_mapping"][idx]
answer = answers[sample_idx]["text"][0]

decoded_example = tokenizer.decode(inputs["input_ids"][idx])
print(f"Theoretical answer: {answer}, decoded example: {decoded_example}")

Theoretical answer: By incorporating multifunctional spaces, projects can reduce the overall building area and optimize space usage, thereby lowering energy and water demands and creating a more efficient, adaptable design., decoded example: [CLS] In what ways might multifunctional spaces contribute to the Integrative Process? [SEP], thermal comfort ranges, and plug load demands are analyzed to identify opportunities for energy efficiency. Documentation of how these analyses inform decisions is then reflected in the project ’ s form, geometry, and building envelope features, often resulting in significant downsizing or simplification of building systems such as HVAC, lighting, and other controls. [SEP]

In [240]:
max_length = 384
stride = 128


def preprocess_training_examples(examples):
    questions = [q.strip() for q in examples["question"]]
    inputs = tokenizer(
        questions,
        examples["context"],
        max_length=max_length,
        truncation="only_second",
        stride=stride,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    offset_mapping = inputs.pop("offset_mapping")
    sample_map = inputs.pop("overflow_to_sample_mapping")
    answers = examples["answer_idx"]
    start_positions = []
    end_positions = []

    for i, offset in enumerate(offset_mapping):
        sample_idx = sample_map[i]
        answer = answers[sample_idx]
        start_char = answer["answer_start"][0]
        end_char = answer["answer_start"][0] + len(answer["text"][0])
        sequence_ids = inputs.sequence_ids(i)

        # Find the start and end of the context
        idx = 0
        while sequence_ids[idx] != 1:
            idx += 1
        context_start = idx
        while sequence_ids[idx] == 1:
            idx += 1
        context_end = idx - 1

        # If the answer is not fully inside the context, label is (0, 0)
        if offset[context_start][0] > start_char or offset[context_end][1] < end_char:
            start_positions.append(0)
            end_positions.append(0)
        else:
            # Otherwise it's the start and end token positions
            idx = context_start
            while idx <= context_end and offset[idx][0] <= start_char:
                idx += 1
            start_positions.append(idx - 1)

            idx = context_end
            while idx >= context_start and offset[idx][1] >= end_char:
                idx -= 1
            end_positions.append(idx + 1)

    inputs["start_positions"] = start_positions
    inputs["end_positions"] = end_positions
    return inputs

In [241]:
train_dataset = raw_datasets["train"].map(
    preprocess_training_examples,
    batched=True,
    remove_columns=raw_datasets["train"].column_names,
)
len(raw_datasets["train"]), len(train_dataset)

Map:   0%|          | 0/64 [00:00<?, ? examples/s]

(64, 64)

In [242]:
print(train_dataset[0])

{'input_ids': [101, 2009, 1110, 1122, 1696, 1106, 3644, 1657, 3626, 1112, 3607, 1111, 6487, 117, 23600, 117, 1137, 1447, 23406, 1107, 1103, 14895, 22472, 4026, 8063, 4755, 136, 102, 1109, 14895, 22472, 4026, 8063, 4755, 1110, 1330, 1696, 6552, 1104, 1103, 149, 1942, 6459, 117, 25055, 122, 1106, 123, 1827, 1106, 3203, 1115, 3644, 4801, 1193, 7246, 4508, 117, 2456, 8715, 25596, 1103, 14769, 3772, 1104, 1718, 119, 1109, 4755, 3272, 1160, 6665, 131, 25338, 14829, 1113, 2331, 1872, 1657, 1137, 11027, 1657, 1115, 1674, 1136, 2283, 9173, 1111, 15750, 117, 1216, 1112, 5748, 17790, 117, 7870, 18220, 1116, 117, 1137, 10902, 1111, 11532, 1530, 119, 1188, 3636, 8559, 1106, 1447, 3470, 1105, 20432, 117, 8753, 170, 5867, 20232, 1104, 1620, 1623, 1111, 1447, 3470, 1105, 1851, 1623, 1111, 20432, 119, 21454, 14485, 1111, 1142, 4755, 1538, 1129, 5784, 1106, 3644, 1657, 3626, 1112, 3607, 1111, 6487, 117, 23600, 117, 1137, 1447, 23406, 119, 14895, 22472, 10902, 1132, 3393, 1118, 7225, 1176, 1103, 158, 119, 156, 119, 5135, 27290, 1174, 11763, 2173, 117, 7009, 1708, 22552, 5393, 1116, 117, 1137, 4976, 1469, 4473, 117, 13291, 3636, 1111, 8018, 23600, 1105, 1530, 119, 1370, 3203, 1113, 2331, 1872, 1657, 1137, 1343, 1115, 2283, 7246, 1657, 4473, 117, 3137, 8313, 1336, 1129, 2148, 1439, 1103, 9467, 20232, 10490, 119, 1636, 8313, 1132, 7458, 1106, 4801, 1193, 4615, 2193, 1956, 117, 1216, 1112, 4142, 11639, 10843, 117, 2900, 2582, 6912, 117, 1105, 1353, 8650, 1116, 1111, 1470, 22345, 119, 8154, 25916, 1116, 1132, 1189, 1111, 9305, 20981, 1137, 5694, 2863, 1359, 1113, 170, 26281, 25758, 1204, 8670, 1105, 3058, 2427, 1231, 16418, 2116, 3268, 117, 1114, 1103, 2273, 1104, 18306, 2379, 1877, 1229, 4374, 10940, 2469, 1111, 1459, 4713, 119, 1650, 2309, 1103, 14895, 22472, 4026, 8063, 9173, 117, 3203, 8681, 1106, 149, 27073, 2137, 787, 188, 1166, 1813, 7520, 2862, 1106, 3689, 10940, 3911, 1115, 3244, 1105, 11778, 1469, 23600, 117, 1231, 20080, 4199, 15298, 5494, 2379, 3979, 117, 1105, 4851, 4801, 18126, 1194, 17873, 1751, 4557, 1105, 10149, 10700, 119, 114, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'start_positions': 52, 'end_positions': 74}

In [244]:
def preprocess_validation_examples(examples):
    questions = [q.strip() for q in examples["question"]]
    inputs = tokenizer(
        questions,
        examples["context"],
        max_length=max_length,
        truncation="only_second",
        stride=stride,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    sample_map = inputs.pop("overflow_to_sample_mapping")
    example_ids = []

    for i in range(len(inputs["input_ids"])):
        sample_idx = sample_map[i]
        example_ids.append(examples["id"][sample_idx])

        sequence_ids = inputs.sequence_ids(i)
        offset = inputs["offset_mapping"][i]
        inputs["offset_mapping"][i] = [
            o if sequence_ids[k] == 1 else None for k, o in enumerate(offset)
        ]

    inputs["example_id"] = example_ids
    return inputs
# example_ids = []
# def preprocess_validation_examples(examples, unique_id_start=1):
#     """
#     Preprocess validation examples and generate unique IDs for each example.

#     Parameters:
#     - examples: The dataset examples containing 'question', 'context', etc.
#     - unique_id_start: Starting value for generating unique IDs.

#     Returns:
#     - Tokenized inputs with generated unique example IDs.
#     """
#     questions = [q.strip() for q in examples["question"]]
#     inputs = tokenizer(
#         questions,
#         examples["context"],
#         max_length=max_length,
#         truncation="only_second",
#         stride=stride,
#         return_overflowing_tokens=True,
#         return_offsets_mapping=True,
#         padding="max_length",
#     )

#     sample_map = inputs.pop("overflow_to_sample_mapping")
#     #global example_ids

#     # Counter for unique ID generation
#     current_id = unique_id_start

#     for i in range(len(inputs["input_ids"])):
#         # Generate a unique ID
#         unique_id = f"unique-{current_id}"
#         current_id += 1
#         example_ids.append(unique_id)  # Append the generated unique ID

#         sequence_ids = inputs.sequence_ids(i)
#         offset = inputs["offset_mapping"][i]
#         inputs["offset_mapping"][i] = [
#             o if sequence_ids[k] == 1 else None for k, o in enumerate(offset)
#         ]

#     inputs["example_id"] = example_ids
#     return inputs

In [245]:
validation_dataset = raw_datasets["validation"].map(
    preprocess_validation_examples,
    batched=True,
    remove_columns=raw_datasets["validation"].column_names,
)
len(raw_datasets["validation"]), len(validation_dataset)

Map:   0%|          | 0/16 [00:00<?, ? examples/s]

(16, 17)

In [246]:
validation_dataset

Dataset({
    features: ['input_ids', 'token_type_ids', 'attention_mask', 'offset_mapping', 'example_id'],
    num_rows: 17
})

In [247]:
small_eval_set = raw_datasets["validation"].select(range(4))
trained_checkpoint = "distilbert-base-cased-distilled-squad"

tokenizer = AutoTokenizer.from_pretrained(trained_checkpoint)
eval_set = small_eval_set.map(
    preprocess_validation_examples,
    batched=True,
    remove_columns=raw_datasets["validation"].column_names,
)

Map:   0%|          | 0/4 [00:00<?, ? examples/s]

In [248]:
eval_set

Dataset({
    features: ['input_ids', 'attention_mask', 'offset_mapping', 'example_id'],
    num_rows: 4
})

In [249]:
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

In [250]:
import tensorflow as tf
from transformers import TFAutoModelForQuestionAnswering

eval_set_for_model = eval_set.remove_columns(["example_id", "offset_mapping"])
eval_set_for_model.set_format("numpy")

batch = {k: eval_set_for_model[k] for k in eval_set_for_model.column_names}
trained_model = TFAutoModelForQuestionAnswering.from_pretrained(trained_checkpoint)

outputs = trained_model(**batch)

All PyTorch model weights were used when initializing TFDistilBertForQuestionAnswering.

All the weights of TFDistilBertForQuestionAnswering were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForQuestionAnswering for predictions without further training.

In [251]:
start_logits = outputs.start_logits.numpy()
end_logits = outputs.end_logits.numpy()

In [252]:
import collections

example_to_features = collections.defaultdict(list)
for idx, feature in enumerate(eval_set):
    example_to_features[feature["example_id"]].append(idx)

In [253]:
small_eval_set

Dataset({
    features: ['question', 'answers', 'context', 'answer_idx', 'id', '__index_level_0__'],
    num_rows: 4
})

In [254]:
import numpy as np

n_best = 20
max_answer_length = 30
predicted_answers = []

for example in small_eval_set:
    example_id = example["id"]
    context = example["context"]
    answers = []

    for feature_index in example_to_features[example_id]:
        start_logit = start_logits[feature_index]
        end_logit = end_logits[feature_index]
        offsets = eval_set["offset_mapping"][feature_index]

        start_indexes = np.argsort(start_logit)[-1 : -n_best - 1 : -1].tolist()
        end_indexes = np.argsort(end_logit)[-1 : -n_best - 1 : -1].tolist()
        for start_index in start_indexes:
            for end_index in end_indexes:
                # Skip answers that are not fully in the context
                if offsets[start_index] is None or offsets[end_index] is None:
                    continue
                # Skip answers with a length that is either < 0 or > max_answer_length.
                if (
                    end_index < start_index
                    or end_index - start_index + 1 > max_answer_length
                ):
                    continue

                answers.append(
                    {
                        "text": context[offsets[start_index][0] : offsets[end_index][1]],
                        "logit_score": start_logit[start_index] + end_logit[end_index],
                    }
                )

    best_answer = max(answers, key=lambda x: x["logit_score"])
    predicted_answers.append({"id": example_id, "prediction_text": best_answer["text"]})

In [255]:
import evaluate

metric = evaluate.load("squad")

RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
This version of TensorFlow Probability requires TensorFlow version >= 2.14; Detected an installation of version 2.11.0. Please upgrade TensorFlow to proceed.

In [256]:
theoretical_answers = [
    {"id": ex["id"], "answers": ex["answers"]} for ex in small_eval_set
]

In [257]:
print(predicted_answers[0])
print(theoretical_answers[0])

{'id': 'unique-1', 'prediction_text': 'primary evaluative criterion in building design, construction, and operational strategies'}
{'id': 'unique-1', 'answers': 'Human health is prioritized to ensure that building design, construction, and operational strategies foster high-performance healing environments for patients, caregivers, and staff.'}

In [258]:
metric.compute(predictions=predicted_answers, references=theoretical_answers)

NameError: name 'metric' is not defined

In [185]:
# answers = raw_datasets.iloc[2:6]["answer_idx"].tolist()
# start_positions = []
# end_positions = []

# for i, offset in enumerate(inputs["offset_mapping"]):
#     sample_idx = inputs["overflow_to_sample_mapping"][i]
#     answer = answers[sample_idx]
#     start_char = answer["answer_start"][0]
#     end_char = answer["answer_start"][0] + len(answer["text"][0])
#     sequence_ids = inputs.sequence_ids(i)

#     # Find the start and end of the context
#     idx = 0
#     while sequence_ids[idx] != 1:
#         idx += 1
#     context_start = idx
#     while sequence_ids[idx] == 1:
#         idx += 1
#     context_end = idx - 1

#     # If the answer is not fully inside the context, label is (0, 0)
#     if offset[context_start][0] > start_char or offset[context_end][1] < end_char:
#         start_positions.append(0)
#         end_positions.append(0)
#     else:
#         # Otherwise it's the start and end token positions
#         idx = context_start
#         while idx <= context_end and offset[idx][0] <= start_char:
#             idx += 1
#         start_positions.append(idx - 1)

#         idx = context_end
#         while idx >= context_start and offset[idx][1] >= end_char:
#             idx -= 1
#         end_positions.append(idx + 1)

# start_positions, end_positions

In [143]:
idx = 0
sample_idx = inputs["overflow_to_sample_mapping"][idx]
answer = answers[sample_idx]["text"][0]

start = start_positions[idx]
end = end_positions[idx]
labeled_answer = tokenizer.decode(inputs["input_ids"][idx][start : end + 1])

print(f"Theoretical answer: {answer}, labels give: {labeled_answer}")

Theoretical answer: Building height is measured vertically from the average elevation of the finished grade to the topmost section of the roof., labels give: any structure with a roof supported by walls or columns, used for residence, business, industry, or other public or private

In [144]:
idx = 0
sample_idx = inputs["overflow_to_sample_mapping"][idx]
answer = answers[sample_idx]["text"][0]

start = start_positions[idx]
end = end_positions[idx]
labeled_answer = tokenizer.decode(inputs["input_ids"][idx][start : end + 1])

print(f"Theoretical answer: {answer}, labels give: {labeled_answer}")

Theoretical answer: Building height is measured vertically from the average elevation of the finished grade to the topmost section of the roof., labels give: any structure with a roof supported by walls or columns, used for residence, business, industry, or other public or private

In [146]:
import pandas as pd

# Example settings
max_length = 384
stride = 128

# Function to process a single example
def preprocess_training_example(row, tokenizer):
    question = row["question"].strip()
    context = row["context"]
    answer = row["answer_idx"]
    inputs = tokenizer(
        question,
        context,
        max_length=max_length,
        truncation="only_second",
        stride=stride,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    offset_mapping = inputs.pop("offset_mapping")
    sample_map = inputs.pop("overflow_to_sample_mapping")
    start_positions = []
    end_positions = []

    for i, offset in enumerate(offset_mapping):
        start_char = answer["answer_start"][0]
        end_char = start_char + len(answer["text"][0])
        sequence_ids = inputs.sequence_ids(i)

        # Find the start and end of the context
        idx = 0
        while sequence_ids[idx] != 1:
            idx += 1
        context_start = idx
        while sequence_ids[idx] == 1:
            idx += 1
        context_end = idx - 1

        # If the answer is not fully inside the context, label is (0, 0)
        if offset[context_start][0] > start_char or offset[context_end][1] < end_char:
            start_positions.append(0)
            end_positions.append(0)
        else:
            # Otherwise it's the start and end token positions
            idx = context_start
            while idx <= context_end and offset[idx][0] <= start_char:
                idx += 1
            start_positions.append(idx - 1)

            idx = context_end
            while idx >= context_start and offset[idx][1] >= end_char:
                idx -= 1
            end_positions.append(idx + 1)

    # Adding start and end positions back to inputs
    inputs["start_positions"] = start_positions
    inputs["end_positions"] = end_positions
    return inputs

# Example DataFrame (convert DatasetDict into a DataFrame)
raw_datasets_train = raw_datasets

# Process each row of the DataFrame
processed_data = raw_datasets_train.apply(
    lambda row: preprocess_training_example(row, tokenizer),
    axis=1
)

# Convert the results into a DataFrame or Series
train_dataset_df = pd.DataFrame(processed_data.tolist())

In [147]:
train_dataset_df

,attention_mask,end_positions,input_ids,start_positions,token_type_ids
0,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...",[28],"[[101, 1327, 1110, 170, 8315, 4267, 28042, 102...",[10],"[[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,..."
1,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...",[59],"[[101, 1327, 1110, 1103, 3719, 1206, 170, 107,...",[29],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
2,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...",[36],"[[101, 1327, 1110, 1103, 107, 1459, 3976, 107,...",[13],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,..."
3,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...",[82],"[[101, 1327, 1674, 1103, 1858, 107, 1901, 107,...",[24],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
4,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...",[41],"[[101, 1327, 14684, 4912, 1538, 1129, 1316, 11...",[24],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
...,...,...,...,...,...
59,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...",[73],"[[101, 1327, 1547, 3333, 1191, 170, 139, 2137,...",[33],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
60,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...",[58],"[[101, 1327, 1674, 107, 11019, 10913, 1200, 20...",[18],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
61,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...",[33],"[[101, 1327, 4454, 1132, 3417, 1962, 1120, 166...",[27],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,..."
62,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...",[69],"[[101, 1327, 1110, 1103, 1514, 3007, 1104, 110...",[27],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
63,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...",[41],"[[101, 1327, 1110, 170, 107, 3510, 1339, 107, ...",[18],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."

In [148]:
# from sklearn.model_selection import train_test_split

# # Split the data into training and validation sets
# train_df, validation_df = train_test_split(
#     train_dataset_df,  # The DataFrame containing the processed data
#     test_size=0.2,  # Percentage of the data to be used for validation (e.g., 20%)
#     random_state=42,  # For reproducibility
#     shuffle=True  # Shuffle the data before splitting
# )

# # Split the validation set into validation and test sets
# validation_df, test_df = train_test_split(
#     validation_df,  # The previously created validation DataFrame
#     test_size=0.2,  # Split 50% of the validation set into test data
#     random_state=42,  # For reproducibility
#     shuffle=True  # Shuffle the data before splitting
# )

# # Display the sizes of the splits
# print(f"Training set size: {len(train_df)}")
# print(f"Validation set size: {len(validation_df)}")
# print(f"Test set size: {len(test_df)}")

In [150]:
raw_datasets_val

,question,answers,context,answer_idx
28,How does the Sensitive Land Protection credit ...,By awarding points to projects that avoid envi...,The Sensitive Land Protection credit is anothe...,{'text': ['By awarding points to projects that...
68,What activities can take place in a community ...,Growing food and ornamental crops for personal...,Community gardens are areas used for growing f...,{'text': ['Growing food and ornamental crops f...
35,"What are access trails, and what features migh...",Access trails are pedestrian pathways designed...,"The term ""abut"" refers to properties or land f...",{'text': ['Access trails are pedestrian pathwa...
33,What additional steps are allowed for managing...,Hazardous or dying trees can be removed based ...,For projects on previously developed land or t...,{'text': ['Hazardous or dying trees can be rem...
4,What is the purpose of the preliminary LEED me...,What is the purpose of the preliminary LEED mT...,This integrative process seeks to incorporate ...,{'text': ['What is the purpose of the prelimin...
12,What is the ultimate goal of the integrative p...,The ultimate goal is to create a healthier bui...,"As part of this integrative process, a compreh...",{'text': ['The ultimate goal is to create a he...
22,In what ways might multifunctional spaces cont...,"By incorporating multifunctional spaces, proje...",Energy-related systems are a core focus within...,{'text': ['By incorporating multifunctional sp...
45,How does articulation enhance the visual appea...,Articulation adds variety and visual interest ...,An Area of Special Flood Hazard is land in the...,{'text': ['Articulation adds variety and visua...
18,What role does the water budget analysis play ...,The water budget analysis is crucial for ident...,"In addition to energy, water-related systems r...",{'text': ['The water budget analysis is crucia...
70,What is the purpose of a connection in stormwa...,"To divert or transmit stormwater drainage, imp...","A connection is a structure, such as a ditch o...",{'text': ['To divert or transmit stormwater dr...
49,"What does ""being conducted"" mean in relation t...","""Being conducted"" means that a land-disturbing...","A bedroom is a room designed for sleeping, fur...","{'text': ['""Being conducted"" means that a land..."
67,What is a commercial message?,It is a sign or representation that advertises...,Club or Lodge & Commercial Messaging\nA club o...,{'text': ['It is a sign or representation that...
31,What minor improvements are allowed within the...,Minor improvements such as narrow bicycle path...,For projects on previously developed land or t...,{'text': ['Minor improvements such as narrow b...
10,How long should the design charrette session l...,The design charrette should last a minimum of ...,"As part of this integrative process, a compreh...",{'text': ['The design charrette should last a ...

In [156]:
import uuid

def preprocess_validation_examples_df(df, tokenizer, max_length, stride):
    """
    Preprocess the validation examples for DataFrame input.

    Parameters:
    - df: pd.DataFrame containing 'id', 'question', and 'context'.
    - tokenizer: Tokenizer object to process text.
    - max_length: Maximum token sequence length.
    - stride: Stride length for overlapping tokens.

    Returns:
    - A dictionary with tokenized inputs including offset_mapping and unique example_ids.
    """
    questions = [q.strip() for q in df["question"]]
    contexts = df["context"].tolist()

    # Tokenize the inputs
    inputs = tokenizer(
        questions,
        contexts,
        max_length=max_length,
        truncation="only_second",
        stride=stride,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    sample_map = inputs.pop("overflow_to_sample_mapping")
    example_ids = []

    # Counter for generating unique IDs
    unique_id_counter = 1

    # Process tokenized inputs
    for i in range(len(inputs["input_ids"])):
        # Generate a unique ID
        unique_id = f"example-{unique_id_counter}"
        unique_id_counter += 1
        example_ids.append(unique_id)

        sequence_ids = inputs.sequence_ids(i)
        offset = inputs["offset_mapping"][i]
        inputs["offset_mapping"][i] = [
            o if sequence_ids[k] == 1 else None for k, o in enumerate(offset)
        ]

    inputs["example_id"] = example_ids
    return inputs


# Example usage:
validation_df = raw_datasets_val  # Convert validation set to DataFrame

# Apply preprocessing
processed_validation = preprocess_validation_examples_df(
    validation_df,
    tokenizer=tokenizer,
    max_length=max_length,
    stride=stride,
)

# Convert the processed outputs into a DataFrame for further use
processed_validation_df = pd.DataFrame(processed_validation)

In [161]:
processed_validation

{'input_ids': [[101, 1731, 1674, 1103, 14895, 22472, 4026, 8063, 4755, 1494, 4851, 14769, 3772, 136, 102, 1109, 14895, 22472, 4026, 8063, 4755, 1110, 1330, 1696, 6552, 1104, 1103, 149, 1942, 6459, 117, 25055, 122, 1106, 123, 1827, 1106, 3203, 1115, 3644, 4801, 1193, 7246, 4508, 117, 2456, 8715, 25596, 1103, 14769, 3772, 1104, 1718, 119, 1109, 4755, 3272, 1160, 6665, 131, 25338, 14829, 1113, 2331, 1872, 1657, 1137, 11027, 1657, 1115, 1674, 1136, 2283, 9173, 1111, 15750, 117, 1216, 1112, 5748, 17790, 117, 7870, 18220, 1116, 117, 1137, 10902, 1111, 11532, 1530, 119, 1188, 3636, 8559, 1106, 1447, 3470, 1105, 20432, 117, 8753, 170, 5867, 20232, 1104, 1620, 1623, 1111, 1447, 3470, 1105, 1851, 1623, 1111, 20432, 119, 21454, 14485, 1111, 1142, 4755, 1538, 1129, 5784, 1106, 3644, 1657, 3626, 1112, 3607, 1111, 6487, 117, 23600, 117, 1137, 1447, 23406, 119, 14895, 22472, 10902, 1132, 3393, 1118, 7225, 1176, 1103, 158, 119, 156, 119, 5135, 27290, 1174, 11763, 2173, 117, 7009, 1708, 22552, 5393, 1116, 117, 1137, 4976, 1469, 4473, 117, 13291, 3636, 1111, 8018, 23600, 1105, 1530, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1327, 2619, 1169, 1321, 1282, 1107, 170, 1661, 4605, 136, 102, 3704, 7709, 1132, 1877, 1215, 1111, 2898, 2094, 1137, 20363, 8592, 1111, 2357, 1137, 1372, 1329, 117, 8160, 117, 1137, 14324, 117, 1719, 1107, 2510, 15836, 1137, 14998, 3922, 1174, 119, 6869, 3050, 1132, 3416, 1877, 1439, 170, 1718, 117, 2205, 1118, 1126, 3852, 1137, 23956, 4729, 1818, 5032, 119, 138, 23956, 4729, 1818, 4431, 1106, 1842, 3327, 1114, 8924, 3574, 1111, 2029, 5582, 1105, 1887, 3050, 3416, 14998, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1327, 1132, 2469, 10353, 117, 1105, 1184, 1956, 1547, 1152, 1511, 136, 102, 1109, 1858, 107, 170, 16442, 107, 4431, 1106, 4625, 1137, 1657, 1956, 1115, 1132, 2626, 3387, 1373, 170, 1887, 3070, 119, 1188, 1110, 1510, 1215, 1107, 195, 10087, 1105, 2400, 1644, 1106, 5594, 1103, 2398, 1206, 4903, 4625, 119, 1760, 2469, 7166, 1880, 1110, 170, 2732, 1268, 3525, 1800, 1106, 2771, 1166, 1330, 2400, 1106, 2519, 1147, 1319, 119, 1188, 1110, 3337, 1215, 1165, 170, 2400, 1110, 1657, 6726, 1174, 1137, 14756, 2904, 2469, 1106, 170, 1470, 1812, 119, 11737, 10353, 1132, 16270, 19530, 117, 1134, 1169, 1129, 3033, 1121, 1679, 18854, 1137, 24034, 1200, 18854, 9902, 117, 2011, 1106, 2194, 2469, 1106, 2473, 1447, 1137, 2379, 1877, 119, 1636, 10353, 1336, 1511, 1956, 1216, 1112, 2313, 13868, 1116, 117, 3343, 117, 1289, 12797, 1116, 117, 1105, 2951, 2553, 1106, 11778, 1366, 6328, 1105, 3429, 1111, 16270, 1116, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1327, 2509, 3343, 1132, 2148, 1111, 7204, 20981, 1137, 5694, 2863, 1439, 7246, 1657, 1877, 136, 102, 1370, 3203, 1113, 2331, 1872, 1657, 1137, 1343, 1115, 2283, 7246, 1657, 4473, 117, 3137, 8313, 1336, 1129, 2148, 1439, 1103, 9467, 20232, 10490, 119, 1636, 8313, 1132, 7458, 1106, 4801, 1193, 4615, 2193, 1956, 117, 1216, 1112, 4142, 11639, 10843, 117, 2900, 2582, 6912, 117, 1105, 1353, 8650, 1116, 1111, 1470, 22345, 119, 8154, 25916, 1116, 1132, 1189, 1111, 9305, 20981, 1137, 5694, 2863, 1359, 1113, 170, 26281, 25758, 1204, 8670, 1105, 3058, 2427, 1231, 16418, 2116, 3268, 117, 1114, 1103, 2273, 1104, 18306, 2379, 1877, 1229, 4374, 10940, 2469, 1111, 1459, 4713, 119, 1650, 2309, 1103, 14895, 22472, 4026, 8063, 9173, 117, 3203, 8681, 1106, 149, 27073, 2137, 787, 188, 1166, 1813, 7520, 2862, 1106, 3689, 10940, 3911, 1115, 3244, 1105, 11778, 1469, 23600, 117, 1231, 20080, 4199, 15298, 5494, 2379, 3979, 117, 1105, 4851, 4801, 18126, 1194, 17873, 1751, 4557, 1105, 10149, 10700, 119, 114, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1327, 1110, 1103, 3007, 1104, 1103, 9889, 149, 27073, 2137, 2309, 1107, 12520, 3203, 136, 102, 1188, 1107, 1566, 14867, 3946, 1965, 11053, 1106, 13639, 10940, 1105, 2616, 118, 3903, 2448, 1902, 1105, 2058, 10700, 1114, 170, 4160, 2817, 1113, 1769, 2332, 119, 1650, 9712, 4774, 3408, 2332, 1112, 170, 2425, 174, 7501, 6718, 3946, 26440, 1107, 1459, 1902, 117, 2058, 117, 1105, 6519, 10700, 117, 1142, 3136, 14710, 10034, 5660, 1115, 12100, 1344, 118, 2099, 9523, 10152, 1111, 4420, 117, 1920, 5389, 10704, 117, 1105, 2546, 119, 1370, 12520, 3203, 117, 170, 2771, 118, 9360, 3136, 1538, 1129, 3399, 1346, 1113, 117, 2150, 1121, 4159, 1105, 3073, 118, 1902, 12877, 117, 1106, 4989, 170, 14684, 1965, 1115, 9804, 1121, 7188, 11717, 1106, 5515, 170, 16358, 15105, 117, 2332, 118, 8663, 9386, 119, 1109, 1148, 2585, 1107, 1142, 1965, 1110, 1106, 7034, 1126, 13432, 1200, 787, 188, 4042, 11336, 15174, 4385, 113, 152, 22861, 114, 5830, 117, 1134, 2075, 170, 1218, 118, 3393, 2332, 2862, 4195, 119, 1188, 4195, 1538, 7977, 789, 9225, 3248, 1413, 790, 4718, 1118, 26975, 2670, 117, 4801, 117, 1105, 1934, 11350, 1105, 3545, 2330, 2513, 1111, 1103, 2332, 1104, 1459, 20664, 117, 1103, 1469, 1661, 117, 1105, 1103, 4265, 3750, 119, 1109, 152, 22861, 1105, 2332, 2862, 4195, 1532, 1103, 4686, 1111, 3780, 170, 9523, 118, 3378, 117, 10940, 3750, 14006, 1114, 1103, 2747, 2993, 1104, 1103, 1459, 787, 188, 4713, 119, 5533, 117, 170, 9889, 149, 27073, 2137, 2309, 1538, 1129, 1316, 1112, 1346, 1112, 1936, 117, 7891, 1193, 1196, 188, 4386, 10734, 1902, 117, 5336, 1120, 1655, 1300, 2501, 1933, 1264, 1484, 3338, 1103, 3172, 1137, 3172, 787, 188, 4702, 119, 1188, 2309, 787, 188, 3007, 1110, 1106, 3689, 170, 149, 27073, 2137, 2168, 2197, 1115, 25854, 1103, 8759, 149, 27073, 2137, 12146, 1634, 113, 25777, 117, 4826, 117, 3487, 117, 1137, 16629, 114, 117, 8247, 1116, 1103, 149, 27073, 2137, 6459, 1106, 5515, 1103, 4010, 1634, 117, 1105, 1902, 5430, 1264, 1484, 2784, 1111, 2309, 1296, 3073, 1874, 26089, 1105, 2700, 4755, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1327, 1110, 1103, 10010, 2273, 1104, 1103, 1107, 1566, 14867, 3946, 1965, 1111, 12520, 3203, 136, 102, 1249, 1226, 1104, 1142, 1107, 1566, 14867, 3946, 1965, 117, 170, 8232, 1933, 1264, 1110, 6818, 1106, 2797, 2265, 13950, 119, 1188, 1264, 1431, 8296, 1104, 170, 5867, 1104, 1300, 8799, 3338, 1103, 3172, 1137, 3172, 787, 188, 4702, 117, 4619, 1121, 170, 2079, 1104, 7503, 3872, 1106, 4989, 1126, 24568, 3136, 1106, 1902, 1105, 2383, 118, 1543, 119, 2649, 1484, 1336, 1511, 1103, 3172, 787, 188, 2364, 4788, 2618, 117, 2987, 3806, 117, 5882, 4460, 117, 1459, 5592, 117, 6676, 3806, 117, 2058, 2618, 117, 8649, 3806, 117, 2308, 2235, 1200, 117, 1297, 5120, 2616, 14582, 117, 6659, 1348, 9496, 117, 7570, 5592, 117, 8458, 1105, 2000, 23981, 1116, 117, 26239, 3677, 117, 4801, 1826, 2546, 117, 1105, 2509, 8724, 7503, 1106, 1103, 2747, 1933, 119, 5723, 18137, 1180, 1511, 8974, 1654, 2546, 117, 2094, 1555, 9496, 1116, 117, 1459, 2598, 8799, 117, 1105, 1661, 6683, 119, 1706, 11778, 14684, 3693, 117, 1103, 1933, 1538, 5880, 170, 1902, 22572, 1813, 8127, 1566, 117, 7891, 1193, 1196, 188, 4386, 10734, 1902, 117, 5336, 1155, 1264, 1484, 1111, 170, 5867, 1104, 1300, 2005, 119, 1188, 14684, 4912, 11769, 3121, 19092, 1116, 1103, 9111, 1104, 10940, 10700, 1506, 1155, 10082, 1104, 1103, 1459, 787, 188, 1902, 117, 2058, 117, 1105, 2500, 119, 1650, 24560, 1292, 3343, 117, 12520, 3203, 4989, 170, 17351, 1107, 1566, 14867, 3946, 1965, 1115, 2988, 17030, 11846, 10940, 117, 2332, 118, 8663, 7995, 1229, 4374, 149, 27073, 2137, 12146, 2513, 119, 1188, 3136, 1136, 1178, 11823, 170, 2332, 2852, 1434, 3750, 1111, 4713, 1133, 1145, 6253, 12594, 2332, 1105, 4801, 11350, 1111, 1103, 1661, 1105, 2894, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1130, 1184, 3242, 1547, 4321, 26420, 1348, 6966, 8681, 1106, 1103, 1130, 1566, 14867, 3946, 18821, 136, 102, 5514, 118, 2272, 2344, 1132, 170, 4160, 2817, 1439, 1103, 1130, 1566, 14867, 3946, 18821, 117, 8753, 170, 9889, 2308, 13117, 3622, 117, 1510, 1270, 170, 789, 3014, 2884, 790, 2235, 117, 2063, 1196, 1103, 188, 4386, 10734, 1902, 4065, 119, 1188, 2235, 15187, 1279, 10700, 1106, 4851, 1103, 1459, 787, 188, 2308, 16955, 1118, 13766, 1105, 1231, 24110, 19129, 2272, 1106, 1672, 1902, 3050, 119, 1636, 3050, 1511, 1751, 2975, 117, 1216, 1112, 188, 9574, 1158, 1105, 8786, 7570, 132, 3367, 1158, 1105, 10592, 117, 1134, 2933, 145, 12152, 1658, 27466, 6185, 1105, 7570, 132, 1105, 8148, 11427, 12745, 117, 1176, 22233, 6856, 117, 176, 1742, 6185, 117, 1105, 188, 9574, 1158, 119, 5533, 117, 5320, 1176, 7570, 3001, 117, 10735, 7238, 9123, 117, 1105, 15244, 6829, 7252, 1132, 17689, 1106, 6183, 6305, 1111, 2308, 8096, 119, 11387, 15447, 24832, 1104, 1293, 1292, 18460, 12862, 6134, 1110, 1173, 7226, 1107, 1103, 1933, 787, 188, 1532, 117, 12053, 117, 1105, 1459, 11427, 1956, 117, 1510, 3694, 1107, 2418, 1205, 5053, 6185, 1137, 27466, 8223, 17489, 1104, 1459, 2344, 1216, 1112, 145, 12152, 1658, 117, 7570, 117, 1105, 1168, 7451, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1731, 1674, 1893, 1596, 6856, 11778, 1103, 5173, 5767, 1104, 170, 1459, 136, 102, 1760, 3894, 1104, 3139, 19590, 11679, 18551, 1110, 1657, 1107, 1103, 7870, 18220, 1114, 170, 122, 110, 1137, 3407, 2640, 1104, 9420, 1296, 1214, 117, 1112, 3552, 1118, 177, 19694, 7810, 2233, 119, 2051, 1596, 6856, 1107, 4220, 4431, 1106, 8786, 1459, 3050, 2011, 1106, 2561, 5173, 2199, 117, 1216, 1112, 9507, 3367, 1158, 117, 6535, 1116, 117, 3751, 117, 1105, 12300, 1956, 119, 2051, 21836, 1105, 26460, 6808, 10715, 9506, 1250, 1118, 1126, 2360, 1137, 22009, 1399, 117, 1229, 2051, 21599, 17023, 2075, 1103, 1329, 1104, 1289, 5537, 1105, 11360, 1111, 3780, 1845, 2982, 1137, 2192, 117, 1216, 1112, 2094, 117, 12731, 117, 2720, 117, 1137, 7373, 2982, 119, 2051, 21599, 5863, 1336, 1145, 8803, 17019, 117, 5092, 117, 1105, 3735, 1104, 1103, 2982, 1189, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1327, 1648, 1674, 1103, 1447, 4788, 3622, 1505, 1107, 1103, 1130, 1566, 14867, 3946, 18821, 136, 102, 1130, 1901, 1106, 2308, 117, 1447, 118, 2272, 2344, 4752, 170, 9889, 1447, 4788, 3622, 119, 1188, 3622, 117, 3303, 1196, 188, 4386, 10734, 1902, 117, 15187, 1279, 4069, 1111, 7914, 9814, 1895, 1447, 1329, 1194, 7856, 1902, 1105, 1103, 1329, 1104, 1664, 11439, 1895, 1447, 3509, 117, 1176, 4458, 4669, 117, 5021, 4669, 117, 1137, 14255, 2883, 28027, 1162, 1121, 145, 12152, 1658, 2344, 119, 4434, 7252, 1111, 9287, 19219, 117, 7814, 4508, 25265, 1158, 117, 1105, 1168, 5669, 1216, 1112, 12147, 1137, 16524, 1132, 10056, 1106, 11769, 3121, 19092, 2905, 1447, 8096, 119, 1706, 6388, 1902, 6134, 117, 14371, 1431, 10541, 1293, 1103, 1447, 3622, 4401, 1103, 4557, 1105, 9726, 1104, 185, 7776, 6791, 117, 23198, 17863, 3923, 117, 4458, 4669, 2635, 117, 1105, 4508, 25265, 1158, 2344, 117, 14485, 1106, 4851, 5186, 1447, 4555, 1137, 5671, 4669, 3252, 16955, 119, 1188, 8232, 3136, 23613, 1115, 1103, 1933, 5515, 1116, 188, 10941, 10805, 1905, 1506, 2308, 1105, 1447, 2344, 117, 7773, 1106, 170, 10940, 1105, 2616, 118, 3903, 1459, 1902, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1327, 1110, 1103, 3007, 1104, 170, 3797, 1107, 4162, 4669, 2635, 136, 102, 138, 3797, 1110, 170, 2401, 117, 1216, 1112, 170, 15916, 1137, 9415, 117, 1215, 1106, 23448, 1204, 1137, 21994, 4162, 4669, 12779, 117, 12521, 1118, 4162, 4669, 2635, 5502, 119, 138, 16670, 2984, 113, 1114, 4251, 17309, 114, 1110, 170, 6989, 4544, 4147, 4817, 1176, 4251, 117, 17362, 2982, 117, 1105, 2094, 117, 1114, 4251, 1158, 2930, 1111, 23338, 1105, 1146, 1106, 1210, 2302, 9677, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1327, 1674, 107, 1217, 3303, 107, 1928, 1107, 6796, 1106, 1657, 118, 15958, 2619, 136, 102, 138, 4255, 1110, 170, 1395, 2011, 1111, 5575, 117, 21904, 1114, 170, 1908, 117, 1105, 2075, 1126, 8786, 6300, 1111, 3429, 119, 1135, 1674, 1136, 1511, 1887, 1877, 1176, 1690, 4045, 4895, 1152, 1132, 4857, 21904, 1114, 170, 1908, 119, 6819, 3303, 2086, 170, 1657, 118, 15958, 3246, 1144, 1408, 1133, 1144, 1136, 1870, 1680, 4088, 19428, 15100, 117, 1229, 170, 1129, 9019, 113, 15251, 1654, 114, 4431, 1106, 170, 14858, 1104, 2578, 1434, 1106, 1894, 5817, 5822, 1447, 4235, 1105, 5494, 21814, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1327, 1110, 170, 2595, 3802, 136, 102, 1998, 1137, 9262, 111, 10472, 2508, 11655, 3375, 138, 1526, 1137, 14433, 1110, 170, 3695, 1215, 1118, 1136, 118, 1111, 118, 5022, 3722, 117, 7385, 1178, 1106, 2683, 1496, 1116, 118, 6573, 1484, 1105, 7957, 6065, 117, 1463, 1122, 1169, 1129, 12765, 1106, 1639, 1113, 170, 1664, 118, 2366, 3142, 119, 138, 2595, 3802, 1110, 1251, 2951, 117, 1937, 1158, 117, 7998, 117, 1137, 6368, 1115, 8050, 12986, 13733, 1137, 14710, 170, 1671, 117, 3317, 117, 1137, 1555, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1327, 3137, 8313, 1132, 2148, 1439, 1103, 20232, 10490, 1104, 7246, 4508, 117, 1105, 1725, 136, 102, 1370, 3203, 1113, 2331, 1872, 1657, 1137, 1343, 1115, 2283, 7246, 1657, 

In [ ]:
# def preprocess_validation_examples(examples):
#     questions = [q.strip() for q in examples["question"]]
#     inputs = tokenizer(
#         questions,
#         examples["context"],
#         max_length=max_length,
#         truncation="only_second",
#         stride=stride,
#         return_overflowing_tokens=True,
#         return_offsets_mapping=True,
#         padding="max_length",
#     )

#     sample_map = inputs.pop("overflow_to_sample_mapping")
#     example_ids = []

#     for i in range(len(inputs["input_ids"])):
#         sample_idx = sample_map[i]
#         example_ids.append(examples["id"][sample_idx])

#         sequence_ids = inputs.sequence_ids(i)
#         offset = inputs["offset_mapping"][i]
#         inputs["offset_mapping"][i] = [
#             o if sequence_ids[k] == 1 else None for k, o in enumerate(offset)
#         ]

#     inputs["example_id"] = example_ids
#     return inputs

# validation_dataset = raw_datasets["validation"].map(
#     preprocess_validation_examples,
#     batched=True,
#     remove_columns=raw_datasets["validation"].column_names,
# )
# len(raw_datasets["validation"]), len(validation_dataset)

In [152]:
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

/home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [102]:
validation_df.shape

(12, 5)

In [104]:
small_eval_set = validation_df[0:3]
trained_checkpoint = "distilbert-base-cased-distilled-squad"

tokenizer = AutoTokenizer.from_pretrained(trained_checkpoint)

In [105]:
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

In [128]:
import tensorflow as tf
from transformers import TFAutoModelForQuestionAnswering

eval_set = small_eval_set
eval_set_for_model = eval_set.drop(['end_positions','start_positions','token_type_ids'],axis=1)
eval_set_for_model.to_numpy()

batch = {k: np.array(eval_set_for_model[k].tolist())[0] for k in eval_set_for_model.columns}
trained_model = TFAutoModelForQuestionAnswering.from_pretrained(trained_checkpoint)

outputs = trained_model(**batch)

/home/rkannan/miniconda3/envs/richard_tf/lib/python3.9/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
All PyTorch model weights were used when initializing TFDistilBertForQuestionAnswering.

All the weights of TFDistilBertForQuestionAnswering were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForQuestionAnswering for predictions without further training.

In [129]:
start_logits = outputs.start_logits.numpy()
end_logits = outputs.end_logits.numpy()

In [130]:
import collections

example_to_features = collections.defaultdict(list)
for idx, feature in enumerate(eval_set):
    example_to_features[feature["example_id"]].append(idx)

TypeError: string indices must be integers